from selenium import webdriver
from driver import Driver
import time
def register_test(email="Test@mail.com", password="Test@123"):
    driver = Driver()
    chrome = driver.getDriver()
    print(chrome.title)
    locater = chrome.find_element('class name', 'nav-icon')
    locater.click()
    sign_up = chrome.find_element('link text', 'Create one')
    sign_up.click()
    chrome.find_element('id', 'name').send_keys("Test User")
    time.sleep(1)
    chrome.find_element('id', 'email').send_keys(email)
    time.sleep(1)
    chrome.find_element('id', 'password').send_keys(password)
    time.sleep(1)
    chrome.find_element('id', 'confirmPassword').send_keys(password)
    time.sleep(2)
    chrome.find_element('class name', 'btn-auth').click()
    time.sleep(3)
    print("Registration test completed.",chrome.current_url)
    time.sleep(5)
    # chrome.quit()
if __name__ == "__main__":    register_test()