from selenium import webdriver
import time
def register_test():
    chrome = webdriver.Chrome()
    chrome.get("http://localhost:3000")
    chrome.maximize_window()
    print(chrome.title)
    locater = chrome.find_element('class name', 'nav-icon')
    locater.click()
    sign_up = chrome.find_element('link text', 'Create one')
    sign_up.click()
    chrome.find_element('id', 'name').send_keys("Test User")
    time.sleep(1)
    chrome.find_element('id', 'email').send_keys("test@mail.com")
    time.sleep(1)
    chrome.find_element('id', 'password').send_keys("Test@123")
    time.sleep(1)
    chrome.find_element('id', 'confirmPassword').send_keys("Test@123")
    time.sleep(1)
    chrome.find_element('class name', 'btn-auth').click()
    time.sleep(3)
    print("Registration test completed.",chrome.current_url)
    time.sleep(5)
    # chrome.quit()
if __name__ == "__main__":    register_test()